dist: bionic

env:
  global:
    - IMAGE_NAME=pkskubeflow/ml-pipeline-frontend:0.2.5
    - CODE_TAG=master

arch:
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow-pk/pipelines-0.2.5.git

script:

  - cd pipelines-0.2.5/frontend
  - docker build -t ${IMAGE_NAME} -f Dockerfile .
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${IMAGE_NAME}
