dist: bionic

env:
  global:
    - IMAGE_NAME=pkskubeflow/ml-pipeline-frontend:0.2.5
    - CODE_TAG=0.2.5

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce qemu-user-static
  - wget https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
  - chmod a+x buildx-v0.4.2.linux-amd64
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx-v0.4.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
  - docker version
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker buildx inspect --bootstrap
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow/pipelines.git

script:
  - cd pipelines/frontend
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker buildx build --push --platform linux/amd64,linux/arm64 -t ${IMAGE_NAME} -f Dockerfile .
