dist: bionic

env:
  global:
    - IMAGE_NAME=pkskubeflow/ml-pipeline-frontend:0.2.5
    - CODE_TAG=0.2.5

arch:
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow/pipelines.git

script:

  - cd pipelines/frontend
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker build -t  ${IMAGE_NAME} -f Dockerfile 
